# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pj0CX-CEdIfGo2XUMg5LdIUsXrN3Sl8l
"""

import pandas as pd
baza= {
    "FISH":[ "Abduvohidov Yodgorbek" ,"Joraboyev Behruz", "Yusufjonov Yahyobek", "Mirzahamidov Davronbek", "Zaribov Xabibullo", "Mansurov Sanjarbek", "Mansurov Sardorbek", "Mansurov Kamronbek", "Mahamadzokirov Ziyodjon"],
    "YASHASH JOYI":[ "Qoqon shahar", "Mingbuloq tumani", "Dangara tumani", "Yaypan shahar", "Fargona shahar", "Qoqon shahar", "Qoqon shahar", "Qoqon shahar", "Namangan shahar" ],
     "Yoshi":[ "18", "19", "21", "19", "25", "28", "17", "19", "19"],
     "Ish joyi":["Yoq", "Yoq", "Yoq", "Yoq", "Yoq", "Yoq", "Yoq","Yoq", "Yoq"],
     "Jinsi":["erkak", "erkak", "erkak", "erkak", "erkak", "erkak", "erkak","erkak", "erkak"],
}

Yodgorjon=pd.DataFrame(baza)
print(Yodgorjon)

filtr1=Yodgorjon[Yodgorjon["Yoshi"]=="19"]